
name: Python SDK Wrapper CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
  PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
  LT_SDK_DEBUG: true
  SMARTUI_DEBUG: true

jobs:
  smartui-python-sdk:
    name: Execute Python sdk build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install NPM Dependencies
        run: |
          npm i @lambdatest/smartui-cli

      - name: Install Python Dependencies and Execute Python Wrapper
        run: |
          pip install lambdatest-selenium-driver
          npx smartui --version
          npx smartui config:create smartui-web.json
          npx smartui exec python SmartUI_SDK_LT_hub.py --config smartui-web.json
